"""State definition for the Agentic RAG Subgraph."""

from __future__ import annotations

from typing import Any

from typing_extensions import TypedDict


class RAGSubgraphState(TypedDict):
    """Isolated state flowing through the self-correcting RAG subgraph.

    Fields:
        question: Original user question (never mutated).
        history: Conversation history passed in for context-aware generation.
        transformed_query: Rewritten query produced by transform_query node;
            used as the retrieval query on subsequent retrieve calls.
        documents: All documents returned by the most recent retrieve call
            (serialised as plain dicts for LangGraph compatibility).
        relevant_documents: Subset of documents judged relevant by the
            grade_documents node.
        generation: Answer text generated by the generate node.
        citations: Deduplicated list of source file-paths / identifiers.
        retry_count: Number of query-transformation retries already performed.
            Used as a loop guard — should not exceed MAX_RETRIES (2).
        generation_grade: Verdict from the grade_generation node.
            One of: "grounded_and_useful" | "hallucination" | "not_useful".
    """

    question: str
    history: list[dict[str, str]]
    transformed_query: str
    documents: list[dict[str, Any]]
    relevant_documents: list[dict[str, Any]]
    generation: str
    citations: list[str]
    retry_count: int
    generation_grade: str
